### ISSUE TITLE
作为开发人员，我希望在BoasHouse里面引入微服务，以便于单独治理、发布

### ISSUE THREAD

**Issue by fudaliang** [idcf-boat-house/boat-house-frontend#106]
打算在BoasHouse里面引入微服务，使用spring clou的框架，同时引入运维需要的配置中心、注册中心、安全网关、监控中心，以此实现蓝绿部署、金丝雀发布、滚动升级。

**Comment by pipin** [comment]
能否再拆分得更细化一些？每一项作为一个issue，可以方便排优先级和列入迭代

**Comment by fudaliang** [comment]
微服务是设计风格，他的落地方式是spring cloud。如果使用spring cloud，“配置中心、注册中心、安全网关”是要一起用的。 监控中心可以单独出来。 微服务架构在有收益的场景下，受益者很大！
我计划引入spring cloud，是希望为其他项目提供开箱即用的非功能服务和运维基础
