### ISSUE TITLE
作为移动团队，我希望看到APP流水线的搭建过程，以便应用到实际项目上

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house-frontend#107]
AC：

1. 流水线过程需要包括 编译，构建，测试

2. 完成一次成功的流水线全流程运行（可以在团队的Jenkins环境或BoatHouse主库的Jenkins环境）。

**Comment by zlweicoder** [comment]
AC：

    流水线过程需要包括 编译，构建，测试，发布

DOD：

    一次成功的流水线全流程运行（可以在团队的Jenkins环境或BoatHouse主库的Jenkins环境）
