### ISSUE TITLE
作为PHP技术栈爱好者，我希望搭建PHP的自动化构建流程，以便更多的PHPer能够参与进来

### ISSUE THREAD

**Issue by barontan136** [idcf-boat-house/boat-house-frontend#119]
AC：
1、自动化安装PHP及相关插件（docker化）
2、自动安装superviosr，并启动对外的服务（restful）
扩展AC：
集成自动测试工具，sonar、PHPUnit等等

**Comment by zhouwenyang** [comment]
@barontan136 嗯是的我们有计划把PHP技术栈放进来。
