### ISSUE TITLE
作为运维人员我希望kubernetes集群有对应的监控方案，确保可以对集群整体的监控

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house-frontend#125]
AC：

Heapster + InfluxDB + Grafana

1. 需要搭建好监控应用以及产出对应的操作手册（监控node节点、以及容器性能情况）。
2. 需要交付Yaml文件
3. 需要通过Grafana监控集群情况

**Comment by hawaicai** [comment]
故事点 5

**Comment by yimeng** [comment]
需要搭建好监控应用以及产出对应的操作手册（监控node节点、以及容器性能情况）。done
需要交付Yaml文件 done

需要通过Grafana监控集群情况 未完成

原因：k8s监控故事颗粒度有点大，建议分为三个部分：

1 指标工具
2 监控工具
3 展示端工具

本次完成第一个部分，建议后两个部分分一个或两个迭代完成。
