### ISSUE TITLE
作为开发人员，我觉得需要让db有一个集中的环境，大家的改动可以在经过review后，尽量自动部署

### ISSUE THREAD

**Issue by JenniferJJiang** [idcf-boat-house/boat-house-frontend#129]
1. 每个环境（dev, qa, prod）有一个db server, 每个人组也有自己的一个 dev db server
2. 每个组负责db工作的人自己本地安装mysql，功能测试正常后提交脚本。脚本是增量式的Update_YYYYMMDD.sql，确保db不用重建
3. 有专门的运维人员负责部署scripts，按照Update脚本从最早到最新的文件部署，或者配置一个自动化脚本部署工具
4. 其余开发者只需理解本组db server即可进行后续工作

**Comment by zhouwenyang** [comment]
@JenniferJJiang 读写你的建议，嗯同意你的思路。
我们代码里目前只有一个init.sql
不过后面也是期望可以改成这种多个脚本，每次update都有一个sql脚本，然后数据库也可以增量的自动的update

**Comment by ups216** [comment]
数据库的持续交付这块的建议
1）每个人本地有自己的开发用db环境，用户debug过程中的频繁改动和调试
2）团队有一系列共享的db作为CI/CD环境的数据库，用自动化脚本的方式跟随代码进行升级。

参考这张图
![image](https://user-images.githubusercontent.com/1203500/76275322-f52e1380-62bd-11ea-9523-3b1930e33d46.png)

**Comment by JenniferJJiang** [comment]
[项目引入flyway数据库自动部署工具.docx](https://github.com/idcf-boat-house/boat-house/files/4357625/flyway.docx)
  两位老师，我们一组组长让我研究了一个老师提到的flyaway，我简单写了一下文档，帮忙看一看？谢谢！@zhouwenyang @ups216
