### ISSUE TITLE
作为开发人员，我希望每个服务都是一个独立的仓库，每个仓库都有独立的流水线

### ISSUE THREAD

**Issue by tzm1119** [idcf-boat-house/boat-house-frontend#159]
作为开发人员，我希望每个服务都是一个独立的仓库，每个仓库都有独立的流水线，这样每次提交代码后，可以更快地看到开发环境是否部署成功。

**Comment by cqpaul** [comment]
每个仓库有自己独立的流水线，同时整个项目，也应该被一个外层的流水线管理。
