### ISSUE TITLE
作为开发和运维人员，我希望使用Azure DevOps作为工具链，更好的和Azure相关资源做桥接，以便更好的学习和使用Azure云的各项服务

### ISSUE THREAD

**Issue by JaneConan** [idcf-boat-house/boat-house-frontend#217]
作为开发和运维人员，我希望使用Azure DevOps作为工具链，更好的和Azure相关资源做桥接，以便更好的学习和使用Azure云的各项服务。

**Comment by zhouwenyang** [comment]
@JaneConan 哈哈完全木有问题啊

**Comment by yimeng** [comment]
github action可以免费使用Azure DevOps的pipline
