### ISSUE TITLE
集成禅道软件的项目管理和持续集成功能

### ISSUE THREAD

**Issue by easysoft** [idcf-boat-house/boat-house-frontend#218]
作为boat-house用户，我希望可以集成禅道的工具链，让用户可以有更多的选择。

备注：禅道已经内置了Story、Task、Case、Bug、Code、Commit、Jenkins的构建，可以作为完整的持续集成的工具链来使用。

**Comment by zhouwenyang** [comment]
@easysoft 完全没有问题，可以安排到下一个迭代去做这个事情。

**Comment by zhouwenyang** [comment]
@easysoft 哈哈，我base在青岛兄弟

**Comment by easysoft** [comment]
真是巧，疫情过后一起线下面基。:)

**Comment by zhouwenyang** [comment]
@easysoft 好的没问题啊
