### ISSUE TITLE
作为项目团队成员，可以随时在微信群，通过@robot机器人，以聊天的形式获得各种系统数据。

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house-frontend#29]
最好能支持chatops，推送项目信息到微信中

**Comment by elegant1998** [comment]
验收标准AC：

1. 支持ChatOps流程
2. 支持微信群机器人
3. 机器人可以是定时发送消息，也可以被动触发
4. 支持重启、构建、测试等各类命令操作
5. 支持获取机器状态、进程健康度等各种运维信息
