### ISSUE TITLE
作为系统运维人员，需要为系统添加API Gateway，以对API进行授权、监控、负载均衡、缓存等管理

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house-frontend#47]

**Comment by elegant1998** [comment]
验收标准AC：

1. 采用开源软件
2. 除了最重要的高性能的IO模型和集群方案外， 比如会经常使用的 Dashboard 功能，这个对于运维来说是非常重要的
3. 另外还有日志，监控，安全，服务发现，版本控制等。
4. 需要支持超时，熔断，重试，聚合查询等。
