### ISSUE TITLE
作为运维人员，需要系统添加“服务发现”功能，以便于对服务进行管理

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house-frontend#49]

**Comment by elegant1998** [comment]
验收标准AC：

1. 支持注册和查找服务列表
2. 集成服务配置管理功能
3. 实现服务配置的实时重加载
4. 提供一个服务管理后台，用于管理人员查看服务集群的状态
5. 当服务提供者节点挂掉时，要求服务能够及时取消注册，比便及时通知消费者重新获取服务地址。
6. 当服务提供者新加入时，要求服务中介能及时告知服务消费者，你要不要尝试一下新的服务。
