### ISSUE TITLE
作为开发者，我希望boat-house有统一命名规范管理，以便于快速开发

### ISSUE THREAD

**Issue by liaokevin** [idcf-boat-house/boat-house-frontend#88]
验收标准（AC）：
 1 工程名命名
 2 服务包命名，类命名及package-info
 3 工具链中命名（如在JENKINS，DOCKER镜像，配置中心的命名，等等）

**Comment by zhouwenyang** [comment]
@liaokevin 我看到您的PR了，感谢您的贡献。
这个确实是一个很好的建议！！！
