### ISSUE TITLE
作为用户我需要一个本地版工具链搭建的文档，以便我自己可以在本地测试

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house-frontend#96]

**Comment by zhouwenyang** [comment]
AC：

1. 文档需可以跑通全流程，能完成部署。

**Comment by yimeng** [comment]
需要看下本地的环境是什么样的。操作系统 内存大小 网络环境等。有两种统一的方式：
1 使用docker
2 通过packer用vagrant
如果抛开docker的话，第一步估计要从统一操作系统开始了。
